# Generated by Django 3.1 on 2020-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmi',
            field=models.FloatField(null=True),
        ),
    ]
